#!/bin/bash
source bin/cklib.sh

Version="1.5.1-alpha"
Project="9c-swarm-miner"

echo -e "+-----------------------------------------------------------------------------+"
echo -e "| _________                        __          ____  __.                       "
echo -e "| \_   ___ \_______ ___.__._______/  |_  ____ |    |/ _|____    ______ _____   "
echo -e "| /    \  \/\_  __ <   |  |\____ \   __\/  _ \|      < \__  \  /  ___//     \  "
echo -e "| \     \____|  | \/\___  ||  |_> >  | (  <_> )    |  \ / __ \_\___ \|  Y Y  \ "
echo -e "|  \______  /|__|   / ____||   __/|__|  \____/|____|__ (____  /____  >__|_|  / "
echo -e "|         \/        \/     |__|                       \/    \/     \/      \/  "
echo -e "+-----------------------------------------------------------------------------+"
echo -e "| Project: $Project   | Version: $Version   | Platform: $(cPlatform)"
echo -e "+-----------------------------------------------------------------------------+"
echo -e "> Setup..."
echo -e "| --curl"
echo -e "| --unzip"
echo -e "| --docker"
echo -e "| --docker-compose"
echo -e "| --permissions"
echo -e "+---------------------------------------+"
echo -e "> Loading..."
echo -e "| --settings.conf"
echo -e "| --docker-compose.yml"
echo -e "+---------------------------------------+"
echo -e "> Creating settings.conf..."
echo -e "| --settings.conf"
echo -e "+---------------------------------------+"
echo -e "> Updating docker-compose.yml..."
echo -e "| --settings.conf"
echo -e "| --docker-compose.yml"
echo -e "+---------------------------------------+"
echo -e "> Starting docker..."

echo -e "+---------------------------------------+"
echo -e "> Windows Monitor (Full Log): $R"
echo -e "|    Goto Docker and you can access logging for each individual container $R"
echo -e "> Windows Monitor (Mined Blocks Only): $R"
echo -e "|    Search for Mined a block $R"
echo -e "> Linux Monitor (Full Log): $R"
echo -e "|    docker-compose logs --tail=100 -f $R"
echo -e "> Linux Monitor (Mined Blocks Only): $R"
echo -e "|    docker-compose logs --tail=100 -f | grep -A 10 --color -i 'Mined a block' $R"
echo -e "> Linux Monitor (Mined/Reorg/Append failed events): $R"
echo -e "|    docker-compose logs --tail=1 -f | grep --color -i -E 'Mined a|reorged|Append failed' $R"
echo -e "+---------------------------------------+"